### PR TITLE
@jorinvo: just a typo; and a glitch?

### PR DESCRIPTION
**Pull request by GoLangsam**
Hi @jorinvo - great pleasure to do so.

btw: I've refactored Your crawler a little. 
In particular Your "_implementation that abstracts the coordination using channels_"
Just I fear: You may not like it ...

Wanna  see anyway?

### CODE REVIEW

**Comment by jorinvo** [comment]
Thanks!

And yes, please share your version of the crawler. Don't be afraid! I am not the code I wrote and I don't get offended about changing it. There is never only one right way to do things.

**Comment by GoLangsam** [comment]
Hello @jorinvo
I'm happy You say so.
(And let me confess: I did not expect otherwise, as You are a friendly and gentle person.)

[Here](https://github.com/GoLangsam/pipe/blob/master/examples/httpsyet/README.md) we go.

Just be warned: It's not a quick read. Please make sure You have a little time to digest it well.
(and You may prefer to use a local copy - makes it easier to browse around ... and `diff` stuff ... etc.)

And please know: I am VERY grateful!!! Having this including Your tests helped me A LOT!
( And also inspired me to some improvements in my own stuff. )

**Comment by GoLangsam** [comment]
Hello @jorinvo

Having only corrected a typo in my writings,
all of a sudden I get a very strange fail from Your `TestRun`
[here](travis-ci.org/GoLangsam/pipe/builds/396302525)

I'm dumbfounded.
Do You have any idea?

**Comment by jorinvo** [comment]
Sorry, can't see any errors at the link you posted.

Your solution looks very interesting! I can imagine this being helpful for otherwise difficult concurrency problems. 
For a simple tool such as httpsyet I prefer going with the tools Go's standard library has to offer.

**Comment by GoLangsam** [comment]
Hi dear @jorinvo - many thx for looking.

And please do not get me wrong: Using my stuff for a tool like Yours is *not* what I intend to suggest!
Not at all! I'd never bother You with any PR for this! Not a thought!

Just felt: You deserve to know how helpful Your work was (and still is) for me:

- Spurred me to add 'seen' to my collection - a very fine usecase for sync.Map - and a pattern re-coded so oftenly. 
- Spurred me further to support an attribute in there (I badly forgot in my first try).
- Also: Makes a good case for the flexible bufferer (I found it well hidden in the std sources.)

btw: Your family name suggests You might speak German a little? Just wondering ... :-)

**Comment by GoLangsam** [comment]
> Sorry, can't see any errors at the link you posted.

Please note:
- it happened only once - and I've run *lots* of thest by now.
- I also did another heavy-load test with my `traffic` net - all fine.

This is what it looked like - and I still have no clue.

```
=== RUN   TestRun
--- FAIL: TestRun (0.02s)
        crawler_test.go:120: visited page: page/base
        crawler_test.go:120: visited page: page/empty-sub
        crawler_test.go:120: visited page: tls/base
        crawler_test.go:120: visited page: tls/base2
        crawler_test.go:132: visited page: page/redirect
        crawler_test.go:120: visited page: tls/page-b
        crawler_test.go:120: visited page: tls/page-a
        crawler_test.go:120: visited page: http/redirect-target
        crawler_test.go:120: visited page: http/page-a
        crawler_test.go:482: unexpected errors; expected:
                
                404 http://127.0.0.1:39085/404 on page http://127.0.0.1:43363/sub
                404 http://127.0.0.1:43363/404 on page http://127.0.0.1:43363/base
                404 https://127.0.0.1:43649/404 on page http://127.0.0.1:43363/sub
                got:
                
                404 http://127.0.0.1:43363/404 on page http://127.0.0.1:43363/base
        crawler_test.go:482: unexpected output; expected:
                
                http://127.0.0.1:43363/base http://127.0.0.1:43649/page-a
                http://127.0.0.1:43363/sub http://127.0.0.1:43649/page-c
                got:
                
                http://127.0.0.1:43363/base http://127.0.0.1:43649/page-a
        crawler_test.go:206: failed to visit page: http/page-b
        crawler_test.go:206: failed to visit page: page/sub
        crawler_test.go:206: failed to visit page: page/sub/sub
        crawler_test.go:206: failed to visit page: tls/page-c
=== RUN   TestRunSingle
```
So, at least we shall keep an eye on it.

**Pull request merged**
